/**
 * Catálogo do W3C Markup Validator legado
 * (https://validator.w3.org/docs/errors.html).
 *
 * `%s` substitui os placeholders X/Y/Z (e a/b/c nos modelos ambíguos).
 * A primeira regra que casar vence; estas entram depois das do Nu Checker.
 */
export const MARKUP_VALIDATOR_MESSAGES: Array<readonly [string, string]> = [
  ["length of name must not exceed NAMELEN (%s)", "O comprimento do nome não deve exceder NAMELEN ($1)."],
  ["length of parameter entity name must not exceed NAMELEN less the length of the PERO delimiter (%s)", "O comprimento do nome da entidade parâmetro não deve exceder NAMELEN menos o comprimento do delimitador PERO ($1)."],
  ["length of number must not exceed NAMELEN (%s)", "O comprimento do número não deve exceder NAMELEN ($1)."],
  ["length of attribute value must not exceed LITLEN less NORMSEP (%s)", "O comprimento do valor do atributo não deve exceder LITLEN menos NORMSEP ($1)."],
  ["a name group is not allowed in a parameter entity reference in the prolog", "Um grupo de nomes não é permitido em uma referência a entidade parâmetro no prólogo."],
  ["an entity end in a token separator must terminate an entity referenced in the same group", "O fim de entidade em um separador de token deve terminar uma entidade referenciada no mesmo grupo."],
  ["character %s invalid: only %s and token separators allowed", "Caractere $1 inválido: apenas $2 e separadores de token são permitidos."],
  ["a parameter separator is required after a number that is followed by a name start character", "É necessário um separador de parâmetro após um número seguido de um caractere inicial de nome."],
  ["character %s invalid: only %s and parameter separators allowed", "Caractere $1 inválido: apenas $2 e separadores de parâmetro são permitidos."],
  ["an entity end in a parameter separator must terminate an entity referenced in the same declaration", "O fim de entidade em um separador de parâmetro deve terminar uma entidade referenciada na mesma declaração."],
  ["an entity end is not allowed in a token separator that does not follow a token", "Fim de entidade não é permitido em um separador de token que não segue um token."],
  ["%s is not a valid token here", "$1 não é um token válido aqui."],
  ["a parameter entity reference can only occur in a group where a token could occur", "Uma referência a entidade parâmetro só pode ocorrer em um grupo onde um token poderia ocorrer."],
  ["token %s has already occurred in this group", "O token $1 já ocorreu neste grupo."],
  ["the number of tokens in a group must not exceed GRPCNT (%s)", "O número de tokens em um grupo não deve exceder GRPCNT ($1)."],
  ["an entity end in a literal must terminate an entity referenced in the same literal", "O fim de entidade em um literal deve terminar uma entidade referenciada no mesmo literal."],
  ["character %s invalid: only minimum data characters allowed", "Caractere $1 inválido: apenas caracteres de dados mínimos são permitidos."],
  ["a parameter literal in a data tag pattern must not contain a numeric character reference to a non-SGML character", "Um literal de parâmetro em um padrão de data tag não deve conter referência numérica a um caractere não SGML."],
  ["a parameter literal in a data tag pattern must not contain a numeric character reference to a function character", "Um literal de parâmetro em um padrão de data tag não deve conter referência numérica a um caractere de função."],
  ["a name group is not allowed in a general entity reference in a start tag", "Um grupo de nomes não é permitido em uma referência a entidade geral em uma tag de abertura."],
  ["a name group is not allowed in a general entity reference in the prolog", "Um grupo de nomes não é permitido em uma referência a entidade geral no prólogo."],
  ["%s is not a function name", "$1 não é um nome de função."],
  ["%s is not a character number in the document character set", "$1 não é um número de caractere no conjunto de caracteres do documento."],
  ["parameter entity %s not defined", "Entidade parâmetro $1 não definida."],
  ["general entity %s not defined and no default entity", "Entidade geral $1 não definida e sem entidade padrão."],
  ["RNI delimiter must be followed by name start character", "O delimitador RNI deve ser seguido de um caractere inicial de nome."],
  ["unterminated comment: found end of entity inside comment", "Comentário não terminado: fim de entidade encontrado dentro do comentário."],
  ["comment started here", "O comentário começou aqui."],
  ["only one type of connector should be used in a single group", "Apenas um tipo de conector deve ser usado em um único grupo."],
  ["%s is not a reserved name", "$1 não é um nome reservado."],
  ["%s is not allowed as a reserved name here", "$1 não é permitido como nome reservado aqui."],
  ["length of interpreted minimum literal must not exceed reference LITLEN (%s)", "O comprimento do literal mínimo interpretado não deve exceder o LITLEN de referência ($1)."],
  ["length of tokenized attribute value must not exceed LITLEN less NORMSEP (%s)", "O comprimento do valor de atributo tokenizado não deve exceder LITLEN menos NORMSEP ($1)."],
  ["length of system identifier must not exceed LITLEN (%s)", "O comprimento do identificador de sistema não deve exceder LITLEN ($1)."],
  ["length of interpreted parameter literal must not exceed LITLEN (%s)", "O comprimento do literal de parâmetro interpretado não deve exceder LITLEN ($1)."],
  ["length of interpreted parameter literal in data tag pattern must not exceed DTEMPLEN (%s)", "O comprimento do literal de parâmetro interpretado no padrão de data tag não deve exceder DTEMPLEN ($1)."],
  ["literal is missing closing delimiter", "O literal está sem o delimitador de fechamento."],
  ["%s invalid: only %s and parameter separators are allowed", "$1 inválido: apenas $2 e separadores de parâmetro são permitidos."],
  ["%s invalid: only %s and token separators are allowed", "$1 inválido: apenas $2 e separadores de token são permitidos."],
  ["unknown declaration type %s", "Tipo de declaração desconhecido $1."],
  ["%s declaration not allowed in DTD subset", "Declaração $1 não permitida no subconjunto DTD."],
  ["character %s not allowed in declaration subset", "Caractere $1 não permitido no subconjunto de declaração."],
  ["end of document in DTD subset", "Fim do documento no subconjunto DTD."],
  ["character %s not allowed in prolog", "Caractere $1 não permitido no prólogo."],
  ["end of document in prolog", "Fim do documento no prólogo."],
  ["%s declaration not allowed in prolog", "Declaração $1 não permitida no prólogo."],
  ["%s used both a rank stem and generic identifier", "$1 usado tanto como rank stem quanto como identificador genérico."],
  ["omitted tag minimization parameter can be omitted only if OMITTAG NO is specified", "O parâmetro de minimização de tag omitida só pode ser omitido se OMITTAG NO for especificado."],
  ["element type %s already defined", "Tipo de elemento $1 já definido."],
  ["entity reference with no applicable DTD", "Referência a entidade sem DTD aplicável."],
  ["invalid comment declaration: found %s outside comment but inside comment declaration", "Declaração de comentário inválida: $1 encontrado fora do comentário, mas dentro da declaração de comentário."],
  ["comment declaration started here", "A declaração de comentário começou aqui."],
  ["%s declaration not allowed in instance", "Declaração $1 não permitida na instância."],
  ["non-SGML character not allowed in content", "Caractere não SGML não permitido no conteúdo."],
  ["no current rank for rank stem %s", "Não há rank atual para o rank stem $1."],
  ["duplicate attribute definition list for notation %s", "Lista de definição de atributos duplicada para a notação $1."],
  ["duplicate attribute definition list for element %s", "Lista de definição de atributos duplicada para o elemento $1."],
  ["entity end not allowed in end tag", "Fim de entidade não permitido em tag de fechamento."],
  ["character %s not allowed in end tag", "Caractere $1 não permitido na tag de fechamento."],
  ["%s invalid: only S separators and TAGC allowed here", "$1 inválido: apenas separadores S e TAGC são permitidos aqui."],
  ["character data is not allowed here", "Dados de caracteres não são permitidos aqui."],
  ["document type does not allow element %s here; missing one of %s start-tag", "O tipo de documento não permite o elemento $1 aqui; falta uma tag de abertura de $2."],
  ["document type does not allow element %s here; assuming missing %s start-tag", "O tipo de documento não permite o elemento $1 aqui; presumindo tag de abertura $2 ausente."],
  ["document type does not allow element %s here", "O tipo de documento não permite o elemento $1 aqui."],
  ["no start tag specified for implied empty element %s", "Nenhuma tag de abertura especificada para o elemento vazio implícito $1."],
  ["end tag for %s omitted, but its declaration does not permit this", "Tag de fechamento de $1 omitida, mas a declaração não permite isso."],
  ["start tag was here", "A tag de abertura estava aqui."],
  ["end tag for %s omitted, but OMITTAG NO was specified", "Tag de fechamento de $1 omitida, mas OMITTAG NO foi especificado."],
  ["start tag omitted for element %s with declared content", "Tag de abertura omitida para o elemento $1 com conteúdo declarado."],
  ["end tag for %s which is not finished", "Tag de fechamento para $1, que não está concluído."],
  ["start tag for %s omitted, but its declaration does not permit this", "Tag de abertura de $1 omitida, mas a declaração não permite isso."],
  ["number of open elements exceeds TAGLVL (%s)", "O número de elementos abertos excede TAGLVL ($1)."],
  ["element %s undefined", "Elemento $1 indefinido."],
  ["empty end tag but no open elements", "Tag de fechamento vazia, mas não há elementos abertos."],
  ["%s not finished but containing element ended", "$1 não concluído, mas o elemento contêiner terminou."],
  ["end tag for element %s which is not open", "Tag de fechamento para o elemento $1, que não está aberto."],
  ["internal parameter entity %s cannot be CDATA or SDATA", "A entidade parâmetro interna $1 não pode ser CDATA ou SDATA."],
  ["character %s not allowed in attribute specification list", "Caractere $1 não permitido na lista de especificação de atributos."],
  ["an attribute value must be a literal unless it contains only name characters", "Um valor de atributo deve ser um literal, a menos que contenha apenas caracteres de nome."],
  ["entity end not allowed in attribute specification list except in attribute value literal", "Fim de entidade não permitido na lista de especificação de atributos, exceto no literal do valor do atributo."],
  ["external parameter entity %s cannot be CDATA, SDATA, NDATA or SUBDOC", "A entidade parâmetro externa $1 não pode ser CDATA, SDATA, NDATA ou SUBDOC."],
  ["duplicate declaration of entity %s", "Declaração duplicada da entidade $1."],
  ["duplicate declaration of parameter entity %s", "Declaração duplicada da entidade parâmetro $1."],
  ["a reference to a PI entity is allowed only in a context where a processing instruction could occur", "Uma referência a uma entidade PI só é permitida em um contexto onde uma instrução de processamento poderia ocorrer."],
  ["a reference to a CDATA or SDATA entity is allowed only in a context where a data character could occur", "Uma referência a uma entidade CDATA ou SDATA só é permitida em um contexto onde um caractere de dados poderia ocorrer."],
  ["a reference to a subdocument entity or external data entity is allowed only in a context where a data character could occur", "Uma referência a uma entidade de subdocumento ou entidade de dados externa só é permitida em um contexto onde um caractere de dados poderia ocorrer."],
  ["a reference to a subdocument entity or external data entity is not allowed in replaceable character data", "Uma referência a uma entidade de subdocumento ou entidade de dados externa não é permitida em dados de caracteres substituíveis."],
  ["the number of open entities cannot exceed ENTLVL (%s)", "O número de entidades abertas não pode exceder ENTLVL ($1)."],
  ["a reference to a PI entity is not allowed in replaceable character data", "Uma referência a uma entidade PI não é permitida em dados de caracteres substituíveis."],
  ["entity %s is already open", "A entidade $1 já está aberta."],
  ["short reference map %s not defined", "Mapa de referência curta $1 não definido."],
  ["short reference map in DTD must specify associated element type", "O mapa de referência curta no DTD deve especificar o tipo de elemento associado."],
  ["short reference map in document instance cannot specify associated element type", "O mapa de referência curta na instância do documento não pode especificar o tipo de elemento associado."],
  ["short reference map %s for element %s not defined in DTD", "Mapa de referência curta $1 para o elemento $2 não definido no DTD."],
  ["%s is not a short reference delimiter", "$1 não é um delimitador de referência curta."],
  ["short reference delimiter %s already mapped in this declaration", "Delimitador de referência curta $1 já mapeado nesta declaração."],
  ["no document element", "Nenhum elemento de documento."],
  ["entity end not allowed in processing instruction", "Fim de entidade não permitido em instrução de processamento."],
  ["length of processing instruction must not exceed PILEN (%s)", "O comprimento da instrução de processamento não deve exceder PILEN ($1)."],
  ["missing PIC delimiter", "Delimitador PIC ausente."],
  ["an attribute specification must start with a name or name token", "Uma especificação de atributo deve começar com um nome ou token de nome."],
  ["%s is not a member of a group specified for any attribute", "$1 não é membro de um grupo especificado para nenhum atributo."],
  ["the name and VI delimiter can be omitted from an attribute specification only if SHORTTAG YES is specified", "O nome e o delimitador VI só podem ser omitidos de uma especificação de atributo se SHORTTAG YES for especificado."],
  ["there is no attribute %s", "Não existe o atributo $1."],
  ["an attribute value specification must start with a literal or a name character", "Uma especificação de valor de atributo deve começar com um literal ou um caractere de nome."],
  ["length of name token must not exceed NAMELEN (%s)", "O comprimento do token de nome não deve exceder NAMELEN ($1)."],
  ["an attribute value literal can occur in an attribute specification list only after a VI delimiter", "Um literal de valor de atributo só pode ocorrer em uma lista de especificação de atributos após um delimitador VI."],
  ["duplicate specification of attribute %s", "Especificação duplicada do atributo $1."],
  ["duplicate definition of attribute %s", "Definição duplicada do atributo $1."],
  ["data attribute specification must be omitted if attribute specification list is empty", "A especificação de atributo de dados deve ser omitida se a lista de especificação de atributos estiver vazia."],
  ["marked section end not in marked section declaration", "Fim de seção marcada fora de uma declaração de seção marcada."],
  ["number of open marked sections must not exceed TAGLVL (%s)", "O número de seções marcadas abertas não deve exceder TAGLVL ($1)."],
  ["missing marked section end", "Fim de seção marcada ausente."],
  ["marked section started here", "A seção marcada começou aqui."],
  ["entity end in character data, replaceable character data or ignored marked section", "Fim de entidade em dados de caracteres, dados de caracteres substituíveis ou seção marcada ignorada."],
  ["normalized length of attribute value literal must not exceed LITLEN (%s); length was %s", "O comprimento normalizado do literal do valor do atributo não deve exceder LITLEN ($1); o comprimento era $2."],
  ["syntax of attribute value does not conform to declared value", "A sintaxe do valor do atributo não está em conformidade com o valor declarado."],
  ["character %s is not allowed in the value of attribute %s", "O caractere $1 não é permitido no valor do atributo $2."],
  ["value of attribute %s must be a single token", "O valor do atributo $1 deve ser um único token."],
  ["value of attribute %s invalid: %s cannot start a number token", "Valor do atributo $1 inválido: $2 não pode iniciar um token numérico."],
  ["value of attribute %s invalid: %s cannot start a name", "Valor do atributo $1 inválido: $2 não pode iniciar um nome."],
  ["non-impliable attribute %s not specified but OMITTAG NO and SHORTTAG NO", "Atributo não implícito $1 não especificado, mas OMITTAG NO e SHORTTAG NO."],
  ["required attribute %s not specified", "Atributo obrigatório $1 não especificado."],
  ["first occurrence of CURRENT attribute %s not specified", "Primeira ocorrência do atributo CURRENT $1 não especificada."],
  ["%s is not a notation name", "$1 não é um nome de notação."],
  ["%s is not a general entity name", "$1 não é um nome de entidade geral."],
  ["value of attribute %s cannot be %s; must be one of %s", "O valor do atributo $1 não pode ser $2; deve ser um de $3."],
  ["%s is not a data or subdocument entity", "$1 não é uma entidade de dados ou de subdocumento."],
  ["content model is ambiguous: when no tokens have been matched, both the %s and %s occurrences of %s are possible", "O modelo de conteúdo é ambíguo: quando nenhum token foi correspondente, tanto a ocorrência $1 quanto a $2 de $3 são possíveis."],
  ["content model is ambiguous: when the current token is the %s occurrence of %s, both the %s and %s occurrences of %s are possible", "O modelo de conteúdo é ambíguo: quando o token atual é a ocorrência $1 de $2, tanto a ocorrência $3 quanto a $4 de $5 são possíveis."],
  ["content model is ambiguous: when the current token is the %s occurrence of %s and the innermost containing AND group has been matched, both the %s and %s occurrences of %s are possible", "O modelo de conteúdo é ambíguo: quando o token atual é a ocorrência $1 de $2 e o grupo AND mais interno foi correspondente, tanto a ocorrência $3 quanto a $4 de $5 são possíveis."],
  ["content model is ambiguous: when the current token is the %s occurrence of %s and the innermost %s containing AND groups have been matched, both the %s and %s occurrences of %s are possible", "O modelo de conteúdo é ambíguo: quando o token atual é a ocorrência $1 de $2 e os $3 grupos AND mais internos foram correspondentes, tanto a ocorrência $4 quanto a $5 de $6 são possíveis."],
  ["invalid comment declaration: found character %s outside comment but inside comment declaration", "Declaração de comentário inválida: caractere $1 encontrado fora do comentário, mas dentro da declaração de comentário."],
  ["non SGML character number %s", "Caractere não SGML número $1."],
  ["data or replaceable character data in declaration subset", "Dados ou dados de caracteres substituíveis no subconjunto de declaração."],
  ["ID %s already defined", "ID $1 já definido."],
  ["ID %s first defined here", "ID $1 definido pela primeira vez aqui."],
  ["value of fixed attribute %s not equal to default", "Valor do atributo fixo $1 diferente do padrão."],
  ["character %s is not significant in the reference concrete syntax and so cannot occur in a comment in the SGML declaration", "O caractere $1 não é significativo na sintaxe concreta de referência e por isso não pode ocorrer em um comentário na declaração SGML."],
  ["minimum data of first minimum literal in SGML declaration must be \"ISO 8879:1986\" or \"ISO 8879:1986 (ENR)\" or \"ISO 8879:1986 (WWW)\" not %s", "Os dados mínimos do primeiro literal mínimo na declaração SGML devem ser “ISO 8879:1986” ou “ISO 8879:1986 (ENR)” ou “ISO 8879:1986 (WWW)”, não $1."],
  ["parameter before LCNMSTRT must be NAMING not %s", "O parâmetro antes de LCNMSTRT deve ser NAMING, não $1."],
  ["unexpected entity end in SGML declaration: only %s, S separators and comments allowed", "Fim de entidade inesperado na declaração SGML: apenas $1, separadores S e comentários são permitidos."],
  ["%s invalid: only %s and parameter separators allowed", "$1 inválido: apenas $2 e separadores de parâmetro permitidos."],
  ["magnitude of %s too big", "Magnitude de $1 grande demais."],
  ["character %s is not significant in the reference concrete syntax and so cannot occur in a literal in the SGML declaration except as the replacement of a character reference", "O caractere $1 não é significativo na sintaxe concreta de referência e por isso não pode ocorrer em um literal na declaração SGML, exceto como substituição de uma referência de caractere."],
  ["%s is not a valid syntax reference character number", "$1 não é um número de caractere de referência de sintaxe válido."],
  ["a parameter entity reference cannot occur in an SGML declaration", "Uma referência a entidade parâmetro não pode ocorrer em uma declaração SGML."],
  ["cannot continue because of previous errors", "Não é possível continuar devido a erros anteriores."],
  ["SGML declaration cannot be parsed because the character set does not contain characters having the following numbers in ISO 646: %s", "A declaração SGML não pode ser analisada porque o conjunto de caracteres não contém caracteres com os seguintes números em ISO 646: $1."],
  ["the specified character set is invalid because it does not contain the minimum data characters having the following numbers in ISO 646: %s", "O conjunto de caracteres especificado é inválido porque não contém os caracteres de dados mínimos com os seguintes números em ISO 646: $1."],
  ["character numbers declared more than once: %s", "Números de caracteres declarados mais de uma vez: $1."],
  ["character numbers should have been declared UNUSED: %s", "Números de caracteres deveriam ter sido declarados UNUSED: $1."],
  ["character numbers missing in base set: %s", "Números de caracteres ausentes no conjunto base: $1."],
  ["characters in the document character set with numbers exceeding %s not supported", "Caracteres no conjunto de caracteres do documento com números acima de $1 não são suportados."],
  ["invalid formal public identifier %s: missing //", "Identificador público formal $1 inválido: // ausente."],
  ["invalid formal public identifier %s: no SPACE after public text class", "Identificador público formal $1 inválido: sem SPACE após a classe de texto público."],
  ["invalid formal public identifier %s: invalid public text class", "Identificador público formal $1 inválido: classe de texto público inválida."],
  ["invalid formal public identifier %s: public text language must be a name containing only upper case letters", "Identificador público formal $1 inválido: o idioma do texto público deve ser um nome contendo apenas letras maiúsculas."],
  ["invalid formal public identifer %s: public text display version not permitted with this text class", "Identificador público formal $1 inválido: versão de exibição do texto público não permitida com esta classe de texto."],
  ["invalid formal public identifier %s: extra field", "Identificador público formal $1 inválido: campo extra."],
  ["public text class of public identifier in notation identifier must be NOTATION", "A classe de texto público do identificador público em um identificador de notação deve ser NOTATION."],
  ["base character set %s is unknown", "O conjunto de caracteres base $1 é desconhecido."],
  ["delimiter set is ambiguous: %s and %s can be recognized in the same mode", "O conjunto de delimitadores é ambíguo: $1 e $2 podem ser reconhecidos no mesmo modo."],
  ["characters with the following numbers in the syntax reference character set are significant in the concrete syntax but are not in the document character set: %s", "Caracteres com os seguintes números no conjunto de caracteres de referência de sintaxe são significativos na sintaxe concreta, mas não estão no conjunto de caracteres do documento: $1."],
  ["there is no unique character in the document character set corresponding to character number %s in the syntax reference character set", "Não há caractere único no conjunto de caracteres do documento correspondente ao número de caractere $1 no conjunto de caracteres de referência de sintaxe."],
  ["there is no unique character in the internal character set corresponding to character number %s in the syntax reference character set", "Não há caractere único no conjunto de caracteres interno correspondente ao número de caractere $1 no conjunto de caracteres de referência de sintaxe."],
  ["the character with number %s in ISO 646 is significant but has no representation in the syntax reference character set", "O caractere com número $1 em ISO 646 é significativo, mas não tem representação no conjunto de caracteres de referência de sintaxe."],
  ["capacity set %s is unknown", "O conjunto de capacidade $1 é desconhecido."],
  ["capacity %s already specified", "Capacidade $1 já especificada."],
  ["value of capacity %s exceeds value of TOTALCAP", "O valor da capacidade $1 excede o valor de TOTALCAP."],
  ["syntax %s is unknown", "A sintaxe $1 é desconhecida."],
  ["UCNMSTRT must have the same number of characters as LCNMSTRT", "UCNMSTRT deve ter o mesmo número de caracteres que LCNMSTRT."],
  ["UCNMCHAR must have the same number of characters as LCNMCHAR", "UCNMCHAR deve ter o mesmo número de caracteres que LCNMCHAR."],
  ["number of open subdocuments exceeds quantity specified for SUBDOC parameter in SGML declaration (%s)", "O número de subdocumentos abertos excede a quantidade especificada para o parâmetro SUBDOC na declaração SGML ($1)."],
  ["entity %s declared SUBDOC, but SUBDOC NO specified in SGML declaration", "A entidade $1 foi declarada SUBDOC, mas SUBDOC NO foi especificado na declaração SGML."],
  ["a parameter entity referenced in a parameter separator must end in the same declaration", "Uma entidade parâmetro referenciada em um separador de parâmetro deve terminar na mesma declaração."],
  ["reference to non-existent ID %s", "Referência a ID inexistente $1."],
  ["generic identifier %s used in DTD but not defined", "Identificador genérico $1 usado no DTD, mas não definido."],
  ["%s not finished but document ended", "$1 não concluído, mas o documento terminou."],
  ["cannot continue with subdocument because of previous errors", "Não é possível continuar com o subdocumento devido a erros anteriores."],
  ["no document type declaration; will parse without validation", "Nenhuma declaração de tipo de documento; será analisado sem validação."],
  ["no internal or external document type declaration subset; will parse without validation", "Nenhum subconjunto interno ou externo de declaração de tipo de documento; será analisado sem validação."],
  ["this is not an SGML document", "Isto não é um documento SGML."],
  ["length of start-tag before interpretation of literals must not exceed TAGLEN (%s)", "O comprimento da tag de abertura antes da interpretação de literais não deve exceder TAGLEN ($1)."],
  ["a parameter entity referenced in a token separator must end in the same group", "Uma entidade parâmetro referenciada em um separador de token deve terminar no mesmo grupo."],
  ["the following character numbers are shunned characters that are not significant and so should have been declared UNUSED: %s", "Os seguintes números de caracteres são caracteres evitados que não são significativos e por isso deveriam ter sido declarados UNUSED: $1."],
  ["there is no unique character in the specified document character set corresponding to character number %s in ISO 646", "Não há caractere único no conjunto de caracteres do documento correspondente ao número de caractere $1 em ISO 646."],
  ["length of attribute value must not exceed LITLEN less NORMSEP (-%s)", "O comprimento do valor do atributo não deve exceder LITLEN menos NORMSEP (-$1)."],
  ["length of tokenized attribute value must not exceed LITLEN less NORMSEP (-%s)", "O comprimento do valor de atributo tokenizado não deve exceder LITLEN menos NORMSEP (-$1)."],
  ["concrete syntax scope is INSTANCE but value of %s quantity is less than value in reference quantity set", "O escopo da sintaxe concreta é INSTANCE, mas o valor da quantidade $1 é menor que o valor no conjunto de quantidades de referência."],
  ["public text class of formal public identifier of base character set must be CHARSET", "A classe de texto público do identificador público formal do conjunto de caracteres base deve ser CHARSET."],
  ["public text class of formal public identifier of capacity set must be CAPACITY", "A classe de texto público do identificador público formal do conjunto de capacidade deve ser CAPACITY."],
  ["public text class of formal public identifier of concrete syntax must be SYNTAX", "A classe de texto público do identificador público formal da sintaxe concreta deve ser SYNTAX."],
  ["when there is an MSOCHAR there must also be an MSICHAR", "Quando há um MSOCHAR também deve haver um MSICHAR."],
  ["character number %s in the syntax reference character set was specified as a character to be switched but is not a markup character", "O número de caractere $1 no conjunto de caracteres de referência de sintaxe foi especificado como caractere a ser trocado, mas não é um caractere de marcação."],
  ["character number %s was specified as a character to be switched but is not in the syntax reference character set", "O número de caractere $1 foi especificado como caractere a ser trocado, mas não está no conjunto de caracteres de referência de sintaxe."],
  ["character numbers %s in the document character set have been assigned the same meaning, but this is the meaning of a significant character", "Os números de caracteres $1 no conjunto de caracteres do documento receberam o mesmo significado, mas este é o significado de um caractere significativo."],
  ["character number %s assigned to more than one function", "Número de caractere $1 atribuído a mais de uma função."],
  ["%s is already a function name", "$1 já é um nome de função."],
  ["characters with the following numbers in ISO 646 are significant in the concrete syntax but are not in the document character set: %s", "Caracteres com os seguintes números em ISO 646 são significativos na sintaxe concreta, mas não estão no conjunto de caracteres do documento: $1."],
  ["general delimiter %s consists solely of function characters", "O delimitador geral $1 consiste apenas de caracteres de função."],
  ["letters assigned to LCNMCHAR, UCNMCHAR, LCNMSTRT or UCNMSTRT: %s", "Letras atribuídas a LCNMCHAR, UCNMCHAR, LCNMSTRT ou UCNMSTRT: $1."],
  ["digits assigned to LCNMCHAR, UCNMCHAR, LCNMSTRT or UCNMSTRT: %s", "Dígitos atribuídos a LCNMCHAR, UCNMCHAR, LCNMSTRT ou UCNMSTRT: $1."],
  ["character number %s cannot be assigned to LCNMCHAR, UCNMCHAR, LCNMSTRT or UCNMSTRT because it is RE", "O número de caractere $1 não pode ser atribuído a LCNMCHAR, UCNMCHAR, LCNMSTRT ou UCNMSTRT porque é RE."],
  ["character number %s cannot be assigned to LCNMCHAR, UCNMCHAR, LCNMSTRT or UCNMSTRT because it is RS", "O número de caractere $1 não pode ser atribuído a LCNMCHAR, UCNMCHAR, LCNMSTRT ou UCNMSTRT porque é RS."],
  ["character number %s cannot be assigned to LCNMCHAR, UCNMCHAR, LCNMSTRT or UCNMSTRT because it is SPACE", "O número de caractere $1 não pode ser atribuído a LCNMCHAR, UCNMCHAR, LCNMSTRT ou UCNMSTRT porque é SPACE."],
  ["separator characters assigned to LCNMCHAR, UCNMCHAR, LCNMSTRT or UCNMSTRT: %s", "Caracteres separadores atribuídos a LCNMCHAR, UCNMCHAR, LCNMSTRT ou UCNMSTRT: $1."],
  ["character number %s cannot be switched because it is a Digit, LC Letter or UC Letter", "O número de caractere $1 não pode ser trocado porque é um dígito, letra minúscula ou letra maiúscula."],
  ["pointless for number of characters to be 0", "Não faz sentido o número de caracteres ser 0."],
  ["%s cannot be the replacement for a reference reserved name because it is another reference reserved name", "$1 não pode ser a substituição de um nome reservado de referência porque é outro nome reservado de referência."],
  ["%s cannot be the replacement for a reference reserved name because it is the replacement of another reference reserved name", "$1 não pode ser a substituição de um nome reservado de referência porque já é a substituição de outro nome reservado de referência."],
  ["replacement for reserved name %s already specified", "Substituição para o nome reservado $1 já especificada."],
  ["%s is not a valid name in the declared concrete syntax", "$1 não é um nome válido na sintaxe concreta declarada."],
  ["%s is not a valid short reference delimiter because it has more than one B sequence", "$1 não é um delimitador de referência curta válido porque tem mais de uma sequência B."],
  ["%s is not a valid short reference delimiter because it is adjacent to a character that can occur in a blank sequence", "$1 não é um delimitador de referência curta válido porque está adjacente a um caractere que pode ocorrer em uma sequência em branco."],
  ["length of delimiter %s exceeds NAMELEN (%s)", "O comprimento do delimitador $1 excede NAMELEN ($2)."],
  ["length of reserved name %s exceeds NAMELEN (%s)", "O comprimento do nome reservado $1 excede NAMELEN ($2)."],
  ["character numbers assigned to both LCNMCHAR or UCNMCHAR and LCNMSTRT or UCNMSTRT: %s", "Números de caracteres atribuídos tanto a LCNMCHAR ou UCNMCHAR quanto a LCNMSTRT ou UCNMSTRT: $1."],
  ["when the concrete syntax scope is INSTANCE the syntax reference character set of the declared syntax must be the same as that of the reference concrete syntax", "Quando o escopo da sintaxe concreta é INSTANCE, o conjunto de caracteres de referência de sintaxe da sintaxe declarada deve ser o mesmo da sintaxe concreta de referência."],
  ["end-tag minimization should be O for element with declared content of EMPTY", "A minimização de tag de fechamento deve ser O para elemento com conteúdo declarado EMPTY."],
  ["end-tag minimization should be O for element %s because it has CONREF attribute", "A minimização de tag de fechamento deve ser O para o elemento $1 porque ele tem atributo CONREF."],
  ["element %s has a declared content of EMPTY and a CONREF attribute", "O elemento $1 tem conteúdo declarado EMPTY e um atributo CONREF."],
  ["element %s has a declared content of EMPTY and a NOTATION attribute", "O elemento $1 tem conteúdo declarado EMPTY e um atributo NOTATION."],
  ["declared value of data attribute cannot be ENTITY, ENTITIES, ID, IDREF, IDREFS or NOTATION", "O valor declarado de um atributo de dados não pode ser ENTITY, ENTITIES, ID, IDREF, IDREFS ou NOTATION."],
  ["default value of data attribute cannot be CONREF or CURRENT", "O valor padrão de um atributo de dados não pode ser CONREF ou CURRENT."],
  ["number of attribute names and name tokens (%s) exceeds ATTCNT (%s)", "O número de nomes de atributos e tokens de nome ($1) excede ATTCNT ($2)."],
  ["if the declared value is ID the default value must be IMPLIED or REQUIRED", "Se o valor declarado for ID, o valor padrão deve ser IMPLIED ou REQUIRED."],
  ["the attribute definition list already declared attribute %s as the ID attribute", "A lista de definição de atributos já declarou o atributo $1 como o atributo ID."],
  ["the attribute definition list already declared attribute %s as the NOTATION attribute", "A lista de definição de atributos já declarou o atributo $1 como o atributo NOTATION."],
  ["token %s occurs more than once in attribute definition list", "O token $1 ocorre mais de uma vez na lista de definição de atributos."],
  ["no attributes defined for notation %s", "Nenhum atributo definido para a notação $1."],
  ["notation %s for entity %s undefined", "Notação $1 para a entidade $2 indefinida."],
  ["entity %s undefined in short reference map %s", "Entidade $1 indefinida no mapa de referência curta $2."],
  ["notation %s is undefined but had attribute definition", "A notação $1 está indefinida, mas tinha definição de atributo."],
  ["length of interpreted parameter literal in bracketed text plus the length of the bracketing delimiters must not exceed LITLEN (%s)", "O comprimento do literal de parâmetro interpretado em texto entre colchetes mais o comprimento dos delimitadores não deve exceder LITLEN ($1)."],
  ["length of rank stem plus length of rank suffix must not exceed NAMELEN (%s)", "O comprimento do rank stem mais o comprimento do sufixo de rank não deve exceder NAMELEN ($1)."],
  ["document instance must start with document element", "A instância do documento deve começar com o elemento de documento."],
  ["content model nesting level exceeds GRPLVL (%s)", "O nível de aninhamento do modelo de conteúdo excede GRPLVL ($1)."],
  ["grand total of content tokens exceeds GRPGTCNT (%s)", "O total geral de tokens de conteúdo excede GRPGTCNT ($1)."],
  ["unclosed start-tag requires SHORTTAG YES", "Tag de abertura não fechada exige SHORTTAG YES."],
  ["NET-enabling start-tag requires SHORTTAG YES", "Tag de abertura habilitadora de NET exige SHORTTAG YES."],
  ["unclosed end-tag requires SHORTTAG YES", "Tag de fechamento não fechada exige SHORTTAG YES."],
  ["DTDs other than base allowed only if CONCUR YES or EXPLICIT YES", "DTDs além da base só são permitidos se CONCUR YES ou EXPLICIT YES."],
  ["end of entity other than document entity after document element", "Fim de entidade que não é a entidade do documento após o elemento de documento."],
  ["%s declaration illegal after document element", "Declaração $1 ilegal após o elemento de documento."],
  ["character reference illegal after document element", "Referência de caractere ilegal após o elemento de documento."],
  ["entity reference illegal after document element", "Referência a entidade ilegal após o elemento de documento."],
  ["marked section illegal after document element", "Seção marcada ilegal após o elemento de documento."],
  ["the %s occurrence of %s in the content model for %s cannot be excluded at this point because it is contextually required", "A ocorrência $1 de $2 no modelo de conteúdo de $3 não pode ser excluída neste ponto porque é contextualmente obrigatória."],
  ["the %s occurrence of %s in the content model for %s cannot be excluded because it is neither inherently optional nor a member of an OR group", "A ocorrência $1 de $2 no modelo de conteúdo de $3 não pode ser excluída porque não é inerentemente opcional nem membro de um grupo OR."],
  ["an attribute value specification must be an attribute value literal unless SHORTTAG YES is specified", "Uma especificação de valor de atributo deve ser um literal, a menos que SHORTTAG YES seja especificado."],
  ["value cannot be specified both for notation attribute and content reference attribute", "Não é possível especificar valor ao mesmo tempo para atributo de notação e atributo de referência de conteúdo."],
  ["notation %s already defined", "Notação $1 já definida."],
  ["short reference map %s already defined", "Mapa de referência curta $1 já definido."],
  ["first defined here", "Definido pela primeira vez aqui."],
  ["general delimiter role %s already defined", "Papel de delimitador geral $1 já definido."],
  ["number of ID references in start-tag must not exceed GRPCNT (%s)", "O número de referências a ID na tag de abertura não deve exceder GRPCNT ($1)."],
  ["number of entity names in attribute specification list must not exceed GRPCNT (%s)", "O número de nomes de entidade na lista de especificação de atributos não deve exceder GRPCNT ($1)."],
  ["normalized length of attribute specification list must not exceed ATTSPLEN (%s); length was %s", "O comprimento normalizado da lista de especificação de atributos não deve exceder ATTSPLEN ($1); o comprimento era $2."],
  ["short reference delimiter %s already specified", "Delimitador de referência curta $1 já especificado."],
  ["single character short references were already specified for character numbers: %s", "Referências curtas de um caractere já foram especificadas para os números de caracteres: $1."],
  ["default entity used in entity attribute %s", "Entidade padrão usada no atributo de entidade $1."],
  ["reference to entity %s uses default entity", "A referência à entidade $1 usa a entidade padrão."],
  ["entity %s in short reference map %s uses default entity", "A entidade $1 no mapa de referência curta $2 usa a entidade padrão."],
  ["no DTD %s declared", "Nenhum DTD $1 declarado."],
  ["LPD %s has neither internal nor external subset", "O LPD $1 não tem subconjunto interno nem externo."],
  ["element types have different link attribute definitions", "Os tipos de elemento têm definições de atributos de link diferentes."],
  ["link set %s already defined", "Conjunto de links $1 já definido."],
  ["empty result attribute specification", "Especificação de atributo de resultado vazia."],
  ["no source element type %s", "Nenhum tipo de elemento de origem $1."],
  ["no result element type %s", "Nenhum tipo de elemento de resultado $1."],
  ["end of document in LPD subset", "Fim do documento no subconjunto LPD."],
  ["%s declaration not allowed in LPD subset", "Declaração $1 não permitida no subconjunto LPD."],
  ["ID link set declaration not allowed in simple link declaration subset", "Declaração de conjunto de links por ID não permitida no subconjunto de declaração de link simples."],
  ["link set declaration not allowed in simple link declaration subset", "Declaração de conjunto de links não permitida no subconjunto de declaração de link simples."],
  ["attributes can only be defined for base document element (not %s) in simple link declaration subset", "Atributos só podem ser definidos para o elemento de documento base (não $1) no subconjunto de declaração de link simples."],
  ["a short reference mapping declaration is allowed only in the base DTD", "Uma declaração de mapeamento de referência curta só é permitida no DTD base."],
  ["a short reference use declaration is allowed only in the base DTD", "Uma declaração de uso de referência curta só é permitida no DTD base."],
  ["default value of link attribute cannot be CURRENT or CONREF", "O valor padrão de um atributo de link não pode ser CURRENT ou CONREF."],
  ["declared value of link attribute cannot be ID, IDREF, IDREFS or NOTATION", "O valor declarado de um atributo de link não pode ser ID, IDREF, IDREFS ou NOTATION."],
  ["only fixed attributes can be defined in simple LPD", "Apenas atributos fixos podem ser definidos em um LPD simples."],
  ["only one ID link set declaration allowed in an LPD subset", "Apenas uma declaração de conjunto de links por ID é permitida em um subconjunto LPD."],
  ["no initial link set defined for LPD %s", "Nenhum conjunto de links inicial definido para o LPD $1."],
  ["notation %s not defined in source DTD", "Notação $1 não definida no DTD de origem."],
  ["result document type in simple link specification must be implied", "O tipo de documento de resultado em uma especificação de link simples deve ser implícito."],
  ["simple link requires SIMPLE YES", "Link simples exige SIMPLE YES."],
  ["implicit link requires IMPLICIT YES", "Link implícito exige IMPLICIT YES."],
  ["explicit link requires EXPLICIT YES", "Link explícito exige EXPLICIT YES."],
  ["LPD not allowed before first DTD", "LPD não permitido antes do primeiro DTD."],
  ["DTD not allowed after an LPD", "DTD não permitido após um LPD."],
  ["definition of general entity %s is unstable", "A definição da entidade geral $1 é instável."],
  ["definition of parameter entity %s is unstable", "A definição da entidade parâmetro $1 é instável."],
  ["multiple link rules for ID %s but not all have link attribute specifications", "Várias regras de link para o ID $1, mas nem todas têm especificações de atributo de link."],
  ["multiple link rules for element type %s but not all have link attribute specifications", "Várias regras de link para o tipo de elemento $1, mas nem todas têm especificações de atributo de link."],
  ["link type %s does not have a link set %s", "O tipo de link $1 não tem um conjunto de links $2."],
  ["link set use declaration for simple link process", "Declaração de uso de conjunto de links para processo de link simples."],
  ["no link type %s", "Nenhum tipo de link $1."],
  ["both document type and link type %s", "Tipo de documento e tipo de link $1 ao mesmo tempo."],
  ["link type %s already defined", "Tipo de link $1 já definido."],
  ["document type %s already defined", "Tipo de documento $1 já definido."],
  ["link set %s used in LPD but not defined", "Conjunto de links $1 usado no LPD, mas não definido."],
  ["#IMPLIED already linked to result element type %s", "#IMPLIED já associado ao tipo de elemento de resultado $1."],
  ["number of active simple link processes exceeds quantity specified for SIMPLE parameter in SGML declaration (%s)", "O número de processos de link simples ativos excede a quantidade especificada para o parâmetro SIMPLE na declaração SGML ($1)."],
  ["only one chain of explicit link processes can be active", "Apenas uma cadeia de processos de link explícito pode estar ativa."],
  ["source document type name for link type %s must be base document type since EXPLICIT YES 1", "O nome do tipo de documento de origem para o tipo de link $1 deve ser o tipo de documento base, pois EXPLICIT YES 1."],
  ["only one implicit link process can be active", "Apenas um processo de link implícito pode estar ativo."],
  ["sorry, link type %s not activated: only one implicit or explicit link process can be active (with base document type as source document type)", "O tipo de link $1 não foi ativado: apenas um processo de link implícito ou explícito pode estar ativo (com o tipo de documento base como origem)."],
  ["name missing after name group in entity reference", "Nome ausente após o grupo de nomes na referência a entidade."],
  ["source document type name for link type %s must be base document type since EXPLICIT NO", "O nome do tipo de documento de origem para o tipo de link $1 deve ser o tipo de documento base, pois EXPLICIT NO."],
  ["link process must be activated before base DTD", "O processo de link deve ser ativado antes do DTD base."],
  ["unexpected entity end while starting second pass", "Fim de entidade inesperado ao iniciar a segunda passagem."],
  ["type %s of element with ID %s not associated element type for applicable link rule in ID link set", "O tipo $1 do elemento com ID $2 não é o tipo de elemento associado à regra de link aplicável no conjunto de links por ID."],
  ["DATATAG feature not implemented", "Recurso DATATAG não implementado."],
  ["generic identifier specification missing after document type specification in start-tag", "Especificação de identificador genérico ausente após a especificação de tipo de documento na tag de abertura."],
  ["generic identifier specification missing after document type specification in end-tag", "Especificação de identificador genérico ausente após a especificação de tipo de documento na tag de fechamento."],
  ["a NET-enabling start-tag cannot include a document type specification", "Uma tag de abertura habilitadora de NET não pode incluir uma especificação de tipo de documento."],
  ["DTD did not contain element declaration for document type name", "O DTD não continha declaração de elemento para o nome do tipo de documento."],
  ["invalid default SGML declaration", "Declaração SGML padrão inválida."],
  ["reference to entity %s for which no system identifier could be generated", "Referência à entidade $1 para a qual nenhum identificador de sistema pôde ser gerado."],
  ["entity was defined here", "A entidade foi definida aqui."],
  ["content model is mixed but does not allow #PCDATA everywhere", "O modelo de conteúdo é misto, mas não permite #PCDATA em todos os lugares."],
  ["start or end of range must specify a single character", "O início ou o fim do intervalo deve especificar um único caractere."],
  ["number of first character in range must not exceed number of second character in range", "O número do primeiro caractere no intervalo não deve exceder o número do segundo."],
  ["delimiter cannot be an empty string", "O delimitador não pode ser uma string vazia."],
  ["too many characters assigned same meaning with minimum literal", "Caracteres demais com o mesmo significado atribuído por literal mínimo."],
  ["earlier reference to entity %s used default entity", "Uma referência anterior à entidade $1 usou a entidade padrão."],
  ["empty start-tag", "Tag de abertura vazia."],
  ["empty end-tag", "Tag de fechamento vazia."],
  ["unused short reference map %s", "Mapa de referência curta $1 não utilizado."],
  ["unused parameter entity %s", "Entidade parâmetro $1 não utilizada."],
  ["cannot generate system identifier for public text %s", "Não é possível gerar identificador de sistema para o texto público $1."],
  ["cannot generate system identifier for general entity %s", "Não é possível gerar identificador de sistema para a entidade geral $1."],
  ["cannot generate system identifier for parameter entity %s", "Não é possível gerar identificador de sistema para a entidade parâmetro $1."],
  ["cannot generate system identifier for document type %s", "Não é possível gerar identificador de sistema para o tipo de documento $1."],
  ["cannot generate system identifier for link type %s", "Não é possível gerar identificador de sistema para o tipo de link $1."],
  ["cannot generate system identifier for notation %s", "Não é possível gerar identificador de sistema para a notação $1."],
  ["element type %s both included and excluded", "Tipo de elemento $1 incluído e excluído ao mesmo tempo."],
  ["no document type declaration; implying %s", "Nenhuma declaração de tipo de documento; implicando $1."],
  ["minimum data of AFDR declaration must be \"ISO/IEC 10744:1997\" not %s", "Os dados mínimos da declaração AFDR devem ser “ISO/IEC 10744:1997”, não $1."],
  ["AFDR declaration required before use of AFDR extensions", "Declaração AFDR necessária antes do uso de extensões AFDR."],
  ["ENR extensions were used but minimum literal was not \"ISO 8879:1986 (ENR)\" or \"ISO 8879:1986 (WWW)\"", "Extensões ENR foram usadas, mas o literal mínimo não era “ISO 8879:1986 (ENR)” nem “ISO 8879:1986 (WWW)”."],
  ["illegal numeric character reference to non-SGML character %s in literal", "Referência numérica ilegal ao caractere não SGML $1 em literal."],
  ["cannot convert character reference to number %s because description %s unrecognized", "Não é possível converter a referência de caractere para o número $1 porque a descrição $2 não foi reconhecida."],
  ["cannot convert character reference to number %s because character %s from baseset %s unknown", "Não é possível converter a referência de caractere para o número $1 porque o caractere $2 do conjunto base $3 é desconhecido."],
  ["character reference to number %s cannot be converted because of problem with internal character set", "A referência de caractere para o número $1 não pode ser convertida por problema no conjunto de caracteres interno."],
  ["cannot convert character reference to number %s because character not in internal character set", "Não é possível converter a referência de caractere para o número $1 porque o caractere não está no conjunto interno."],
  ["Web SGML adaptations were used but minimum literal was not \"ISO 8879:1986 (WWW)\"", "Adaptações Web SGML foram usadas, mas o literal mínimo não era “ISO 8879:1986 (WWW)”."],
  ["token %s can be value for multiple attributes so attribute name required", "O token $1 pode ser valor de vários atributos, portanto o nome do atributo é obrigatório."],
  ["length of hex number must not exceed NAMELEN (%s)", "O comprimento do número hexadecimal não deve exceder NAMELEN ($1)."],
  ["CDATA declared content", "Conteúdo declarado CDATA."],
  ["RCDATA declared content", "Conteúdo declarado RCDATA."],
  ["inclusion", "Inclusão."],
  ["exclusion", "Exclusão."],
  ["NUMBER or NUMBERS declared value", "Valor declarado NUMBER ou NUMBERS."],
  ["NAME or NAMES declared value", "Valor declarado NAME ou NAMES."],
  ["NUTOKEN or NUTOKENS declared value", "Valor declarado NUTOKEN ou NUTOKENS."],
  ["CONREF attribute", "Atributo CONREF."],
  ["CURRENT attribute", "Atributo CURRENT."],
  ["TEMP marked section", "Seção marcada TEMP."],
  ["included marked section in the instance", "Seção marcada incluída na instância."],
  ["ignored marked section in the instance", "Seção marcada ignorada na instância."],
  ["RCDATA marked section", "Seção marcada RCDATA."],
  ["processing instruction entity", "Entidade de instrução de processamento."],
  ["bracketed text entity", "Entidade de texto entre colchetes."],
  ["internal CDATA entity", "Entidade CDATA interna."],
  ["internal SDATA entity", "Entidade SDATA interna."],
  ["external CDATA entity", "Entidade CDATA externa."],
  ["external SDATA entity", "Entidade SDATA externa."],
  ["attribute definition list declaration for notation", "Declaração de lista de definição de atributos para notação."],
  ["rank stem", "Rank stem."],
  ["no system id specified", "Nenhum system id especificado."],
  ["comment in parameter separator", "Comentário em separador de parâmetro."],
  ["named character reference", "Referência de caractere nomeada."],
  ["AND group", "Grupo AND."],
  ["attribute value not a literal", "Valor de atributo não é um literal."],
  ["attribute name missing", "Nome de atributo ausente."],
  ["element declaration for group of element types", "Declaração de elemento para grupo de tipos de elemento."],
  ["attribute definition list declaration for group of element types", "Declaração de lista de definição de atributos para grupo de tipos de elemento."],
  ["empty comment declaration", "Declaração de comentário vazia."],
  ["S separator in comment declaration", "Separador S na declaração de comentário."],
  ["multiple comments in comment declaration", "Vários comentários na declaração de comentário."],
  ["no status keyword", "Nenhuma palavra-chave de status."],
  ["multiple status keywords", "Várias palavras-chave de status."],
  ["parameter entity reference in document instance", "Referência a entidade parâmetro na instância do documento."],
  ["element type minimization parameter", "Parâmetro de minimização de tipo de elemento."],
  ["reference not terminated by REFC delimiter", "Referência não terminada pelo delimitador REFC."],
  ["#PCDATA not first in model group", "#PCDATA não é o primeiro no grupo de modelo."],
  ["#PCDATA in SEQ group", "#PCDATA em grupo SEQ."],
  ["#PCDATA in nested model group", "#PCDATA em grupo de modelo aninhado."],
  ["#PCDATA in model group that does not have REP occurrence indicator", "#PCDATA em grupo de modelo que não tem indicador de ocorrência REP."],
  ["name group or name token group used connector other than OR", "Grupo de nomes ou de tokens de nome usou conector diferente de OR."],
  ["processing instruction does not start with name", "A instrução de processamento não começa com um nome."],
  ["S separator in status keyword specification in document instance", "Separador S na especificação de palavra-chave de status na instância do documento."],
  ["reference to external data entity", "Referência a entidade de dados externa."],
  ["reference to external entity in attribute value", "Referência a entidade externa em valor de atributo."],
  ["character %s is the first character of a delimiter but occurred as data", "O caractere $1 é o primeiro caractere de um delimitador, mas ocorreu como dado."],
  ["SGML declaration was not implied", "A declaração SGML não foi implícita."],
  ["marked section in internal DTD subset", "Seção marcada no subconjunto DTD interno."],
  ["NET-enabling start-tag not immediately followed by null end-tag", "Tag de abertura habilitadora de NET não seguida imediatamente por tag de fechamento nula."],
  ["entity end in different element from entity reference", "Fim de entidade em elemento diferente da referência à entidade."],
  ["NETENABL IMMEDNET requires EMPTYNRM YES", "NETENABL IMMEDNET exige EMPTYNRM YES."],
  ["reference to non-SGML character", "Referência a caractere não SGML."],
  ["declaration of default entity", "Declaração de entidade padrão."],
  ["reference to parameter entity in parameter separator in internal subset", "Referência a entidade parâmetro em separador de parâmetro no subconjunto interno."],
  ["reference to parameter entity in token separator in internal subset", "Referência a entidade parâmetro em separador de token no subconjunto interno."],
  ["reference to parameter entity in parameter literal in internal subset", "Referência a entidade parâmetro em literal de parâmetro no subconjunto interno."],
  ["cannot generate system identifier for SGML declaration reference", "Não é possível gerar identificador de sistema para a referência à declaração SGML."],
  ["public text class of formal public identifier of SGML declaration must be SD", "A classe de texto público do identificador público formal da declaração SGML deve ser SD."],
  ["SGML declaration reference was used but minimum literal was not \"ISO 8879:1986 (WWW)\"", "Foi usada referência à declaração SGML, mas o literal mínimo não era “ISO 8879:1986 (WWW)”."],
  ["member of model group containing #PCDATA has occurrence indicator", "Membro de grupo de modelo contendo #PCDATA tem indicador de ocorrência."],
  ["member of model group containing #PCDATA is a model group", "Membro de grupo de modelo contendo #PCDATA é um grupo de modelo."],
  ["reference to non-predefined entity", "Referência a entidade não predefinida."],
  ["reference to external entity", "Referência a entidade externa."],
  ["declaration of default entity conflicts with IMPLYDEF ENTITY YES", "A declaração de entidade padrão conflita com IMPLYDEF ENTITY YES."],
  ["parsing with respect to more than one active doctype not supported", "Análise em relação a mais de um doctype ativo não é suportada."],
  ["cannot have active doctypes and link types at the same time", "Não é possível ter doctypes e tipos de link ativos ao mesmo tempo."],
  ["number of concurrent document instances exceeds quantity specified for CONCUR parameter in SGML declaration (%s)", "O número de instâncias de documento concorrentes excede a quantidade especificada para o parâmetro CONCUR na declaração SGML ($1)."],
  ["datatag group can only be specified in base document type", "Grupo datatag só pode ser especificado no tipo de documento base."],
  ["element not in the base document type can't have an empty start-tag", "Elemento que não está no tipo de documento base não pode ter tag de abertura vazia."],
  ["element not in base document type can't have an empty end-tag", "Elemento que não está no tipo de documento base não pode ter tag de fechamento vazia."],
  ["immediately recursive element", "Elemento imediatamente recursivo."],
  ["invalid URN %s: missing \":\"", "URN $1 inválido: “:” ausente."],
  ["invalid URN %s: missing \"urn:\" prefix", "URN $1 inválido: prefixo “urn:” ausente."],
  ["invalid URN %s: invalid namespace identifier", "URN $1 inválido: identificador de namespace inválido."],
  ["invalid URN %s: invalid namespace specific string", "URN $1 inválido: string específica de namespace inválida."],
  ["invalid URN %s: extra field", "URN $1 inválido: campo extra."],
  ["prolog can't be omitted unless CONCUR NO and LINK EXPLICIT NO and either IMPLYDEF ELEMENT YES or IMPLYDEF DOCTYPE YES", "O prólogo não pode ser omitido a menos que CONCUR NO e LINK EXPLICIT NO e IMPLYDEF ELEMENT YES ou IMPLYDEF DOCTYPE YES."],
  ["can't determine name of #IMPLIED document element", "Não é possível determinar o nome do elemento de documento #IMPLIED."],
  ["can't use #IMPLICIT doctype unless CONCUR NO and LINK EXPLICIT NO", "Não é possível usar doctype #IMPLICIT a menos que CONCUR NO e LINK EXPLICIT NO."],
  ["Sorry, #IMPLIED doctypes not implemented", "Doctypes #IMPLIED não implementados."],
  ["reference to DTD data entity ignored", "Referência a entidade de dados do DTD ignorada."],
  ["notation %s for parameter entity %s undefined", "Notação $1 para a entidade parâmetro $2 indefinida."],
  ["notation %s for external subset undefined", "Notação $1 para o subconjunto externo indefinida."],
  ["attribute %s can't be redeclared", "O atributo $1 não pode ser redeclarado."],
  ["#IMPLICIT attributes have already been specified for notation %s", "Atributos #IMPLICIT já foram especificados para a notação $1."],
  ["a name group is not allowed in a parameter entity reference in a start tag", "Um grupo de nomes não é permitido em uma referência a entidade parâmetro em uma tag de abertura."],
  ["name group in a parameter entity reference in an end tag (SGML forbids them in start tags)", "Grupo de nomes em uma referência a entidade parâmetro em uma tag de fechamento (SGML os proíbe em tags de abertura)."],
  ["if the declared value is NOTATION a default value of CONREF is useless", "Se o valor declarado for NOTATION, um valor padrão CONREF é inútil."],
  ["Sorry, #ALL and #IMPLICIT content tokens not implemented", "Tokens de conteúdo #ALL e #IMPLICIT não implementados."],
];
